POST http://localhost:5286/tibber-developer-test/enter-path
Content-Type: application/json

{
  "start": {
    "x": 10,
    "y": 22
  },
  "commands": [
    {
      "direction": "east",
      "steps": 2
    },
    {
      "direction": "south",
      "steps": 1
    },
    {
      "direction": "east",
      "steps": 2
    },
    {
      "direction": "west",
      "steps": 1
    },
    {
      "direction": "east",
      "steps": 2
    },
    {
      "direction": "north",
      "steps": 3
    }
  ]
}

###
